#não usar TAB apenas SPACE
spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
#Propriedade
greeting-service:
  greeting: "Hello"
  default-value: "World"